#!/usr/bin/env python
import random

"""
This module helps linux users to learn about modules of Python standard library.
Usage:
    - put module file in your home directory
    - add to your .bashrc file
        ./learn_py_modules.py

    That'is it.
    Now, info about some random module would be shown every time you run a new bash shell.

"""

__author__ = 'Dimitriy Kutnyakov'
__email__ = 'd.v.kutnyakov@gmail.com'


class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def print_random_module():
    module = random.choice(modules.keys())
    line = '\n{pymotw_color}PyMOTW:{endc} {name_color}{name}{endc} - ' \
           '{descr_color}{descr}{endc} -- {url_color}{url}{endc}\n'.format(
        name=module,
        descr=modules[module]['description'],
        url=modules[module]['url'],
        pymotw_color=bcolors.BOLD,
        name_color=bcolors.OKGREEN,
        descr_color='',
        url_color=bcolors.UNDERLINE,
        endc=bcolors.ENDC,
    )
    print line


modules = {'BaseHTTPServer': {'description': 'Provides base classes for implementing web servers.',
  'url': 'https://pymotw.com/2/BaseHTTPServer'},
 'ConfigParser': {'description': 'Read/write configuration files similar to Windows INI files',
  'url': 'https://pymotw.com/2/ConfigParser'},
 'Cookie': {'description': 'Working with HTTP cookies from the server side.',
  'url': 'https://pymotw.com/2/Cookie'},
 'EasyDialogs': {'description': 'Provides simple interfaces to Carbon dialogs from Python.',
  'url': 'https://pymotw.com/2/EasyDialogs'},
 'Queue': {'description': 'Provides a thread-safe FIFO implementation',
  'url': 'https://pymotw.com/2/Queue'},
 'SimpleXMLRPCServer': {'description': 'Implements an XML-RPC server.',
  'url': 'https://pymotw.com/2/SimpleXMLRPCServer'},
 'SocketServer': {'description': 'Creating network servers.',
  'url': 'https://pymotw.com/2/SocketServer'},
 'StringIO': {'description': 'Work with text buffers using file-like API',
  'url': 'https://pymotw.com/2/StringIO'},
 'abc': {'description': 'Abstract Base Classes',
  'url': 'https://pymotw.com/2/abc'},
 'anydbm': {'description': 'anydbm provides a generic dictionary-like interface to DBM-style, string-keyed databases',
  'url': 'https://pymotw.com/2/anydbm'},
 'argparse': {'description': 'Command line option and argument parsing.',
  'url': 'https://pymotw.com/2/argparse'},
 'array': {'description': 'Manage sequences of fixed-type numerical data efficiently.',
  'url': 'https://pymotw.com/2/array'},
 'asynchat': {'description': 'Asynchronous protocol handler',
  'url': 'https://pymotw.com/2/asynchat'},
 'asyncore': {'description': 'Asynchronous I/O handler',
  'url': 'https://pymotw.com/2/asyncore'},
 'atexit': {'description': 'Register function(s) to be called when a program is closing down.',
  'url': 'https://pymotw.com/2/atexit'},
 'base64': {'description': 'Encode binary data into ASCII characters.',
  'url': 'https://pymotw.com/2/base64'},
 'bisect': {'description': 'Maintains a list in sorted order without having to call sort each time an item is added to the list.',
  'url': 'https://pymotw.com/2/bisect'},
 'bz2': {'description': 'bzip2 compression',
  'url': 'https://pymotw.com/2/bz2'},
 'calendar': {'description': 'The calendar module implements classes for working with dates to manage year/month/week oriented values.',
  'url': 'https://pymotw.com/2/calendar'},
 'cgitb': {'description': 'Mis-named module that provides extended traceback information.',
  'url': 'https://pymotw.com/2/cgitb'},
 'cmd': {'description': 'Create line-oriented command processors.',
  'url': 'https://pymotw.com/2/cmd'},
 'codecs': {'description': 'String encoding and decoding.',
  'url': 'https://pymotw.com/2/codecs'},
 'collections': {'description': 'Container data types.',
  'url': 'https://pymotw.com/2/collections'},
 'commands': {'description': 'Run external shell commands and capture the status code and output.',
  'url': 'https://pymotw.com/2/commands'},
 'compileall': {'description': 'Byte-compile Source Files',
  'url': 'https://pymotw.com/2/compileall'},
 'contextlib': {'description': 'Utilities for creating and working with context managers.',
  'url': 'https://pymotw.com/2/contextlib'},
 'copy': {'description': 'Provides functions for duplicating objects using shallow or deep copy semantics.',
  'url': 'https://pymotw.com/2/copy'},
 'csv': {'description': 'Read and write comma separated value files.',
  'url': 'https://pymotw.com/2/csv'},
 'datetime': {'description': 'Date/time value manipulation.',
  'url': 'https://pymotw.com/2/datetime'},
 'dbhash': {'description': 'DBM-style API for the BSD database library',
  'url': 'https://pymotw.com/2/dbhash'},
 'dbm': {'description': 'Simple database interface',
  'url': 'https://pymotw.com/2/dbm'},
 'decimal': {'description': 'Fixed and floating point math',
  'url': 'https://pymotw.com/2/decimal'},
 'difflib': {'description': 'Compare sequences, especially lines of text.',
  'url': 'https://pymotw.com/2/difflib'},
 'dircache': {'description': 'Cache directory listings',
  'url': 'https://pymotw.com/2/dircache'},
 'dis': {'description': 'Python Bytecode Disassembler',
  'url': 'https://pymotw.com/2/dis'},
 'doctest': {'description': 'Write automated tests as part of the documentation for a module.',
  'url': 'https://pymotw.com/2/doctest'},
 'dumbdbm': {'description': 'Portable DBM Implementation',
  'url': 'https://pymotw.com/2/dumbdbm'},
 'exceptions': {'description': 'Built-in error classes',
  'url': 'https://pymotw.com/2/exceptions'},
 'filecmp': {'description': 'Compare files and directories on the filesystem.',
  'url': 'https://pymotw.com/2/filecmp'},
 'fileinput': {'description': 'Process lines from input streams.',
  'url': 'https://pymotw.com/2/fileinput'},
 'fnmatch': {'description': 'Compare filenames against Unix-style glob patterns.',
  'url': 'https://pymotw.com/2/fnmatch'},
 'fractions': {'description': 'Implements a class for working with rational numbers.',
  'url': 'https://pymotw.com/2/fractions'},
 'functools': {'description': 'Tools for working with functions.',
  'url': 'https://pymotw.com/2/functools'},
 'gc': {'description': 'Garbage Collector', 'url': 'https://pymotw.com/2/gc'},
 'gdbm': {'description': "GNU's version of the dbm library",
  'url': 'https://pymotw.com/2/gdbm'},
 'getopt': {'description': 'Command line option parsing',
  'url': 'https://pymotw.com/2/getopt'},
 'getpass': {'description': 'Prompt the user for a value, usually a password, without echoing what they type to the console.',
  'url': 'https://pymotw.com/2/getpass'},
 'gettext': {'description': 'Message Catalogs',
  'url': 'https://pymotw.com/2/gettext'},
 'glob': {'description': 'Use Unix shell rules to fine filenames matching a pattern.',
  'url': 'https://pymotw.com/2/glob'},
 'grp': {'description': 'Unix Group Database',
  'url': 'https://pymotw.com/2/grp'},
 'gzip': {'description': 'Read and write gzip files',
  'url': 'https://pymotw.com/2/gzip'},
 'hashlib': {'description': 'Cryptographic hashes and message digests',
  'url': 'https://pymotw.com/2/hashlib'},
 'heapq': {'description': 'In-place heap sort algorithm',
  'url': 'https://pymotw.com/2/heapq'},
 'hmac': {'description': 'Cryptographic signature and verification of messages.',
  'url': 'https://pymotw.com/2/hmac'},
 'imaplib': {'description': 'IMAP4 client library',
  'url': 'https://pymotw.com/2/imaplib'},
 'imp': {'description': 'Interface to module import mechanism.',
  'url': 'https://pymotw.com/2/imp'},
 'inspect': {'description': 'Inspect live objects',
  'url': 'https://pymotw.com/2/inspect'},
 'itertools': {'description': 'Iterator functions for efficient looping',
  'url': 'https://pymotw.com/2/itertools'},
 'json': {'description': 'JavaScript Object Notation Serializer',
  'url': 'https://pymotw.com/2/json'},
 'linecache': {'description': 'Retrieve lines of text from files or imported python modules, holding a cache of the results to make reading many lines from the same file more efficient.',
  'url': 'https://pymotw.com/2/linecache'},
 'locale': {'description': 'POSIX cultural localization API',
  'url': 'https://pymotw.com/2/locale'},
 'logging': {'description': 'Report status, error, and informational messages.',
  'url': 'https://pymotw.com/2/logging'},
 'mailbox': {'description': 'Access and manipulate email archives.',
  'url': 'https://pymotw.com/2/mailbox'},
 'math': {'description': 'Mathematical functions',
  'url': 'https://pymotw.com/2/math'},
 'mhlib': {'description': 'Work with MH mailboxes',
  'url': 'https://pymotw.com/2/mhlib'},
 'mmap': {'description': 'Memory-map files',
  'url': 'https://pymotw.com/2/mmap'},
 'multiprocessing': {'description': 'Manage processes like threads.',
  'url': 'https://pymotw.com/2/multiprocessing'},
 'operator': {'description': 'Functional interface to built-in operators',
  'url': 'https://pymotw.com/2/operator'},
 'optparse': {'description': 'Command line option parser to replace :mod:`getopt`.',
  'url': 'https://pymotw.com/2/optparse'},
 'os': {'description': 'Portable access to operating system specific features.',
  'url': 'https://pymotw.com/2/os'},
 'pdb': {'description': 'Interactive Debugger',
  'url': 'https://pymotw.com/2/pdb'},
 'pickle': {'description': 'Python object serialization',
  'url': 'https://pymotw.com/2/pickle'},
 'pipes': {'description': 'Unix shell command pipeline templates',
  'url': 'https://pymotw.com/2/pipes'},
 'pkgutil': {'description': 'Package utilities',
  'url': 'https://pymotw.com/2/pkgutil'},
 'platform': {'description': 'Access system hardware, OS, and interpreter version information.',
  'url': 'https://pymotw.com/2/platform'},
 'plistlib': {'description': 'Manipulate OS X property list files',
  'url': 'https://pymotw.com/2/plistlib'},
 'pprint': {'description': 'Pretty-print data structures',
  'url': 'https://pymotw.com/2/pprint'},
 'profile': {'description': 'Performance analysis of Python programs.',
  'url': 'https://pymotw.com/2/profile'},
 'pwd': {'description': 'Unix Password Database',
  'url': 'https://pymotw.com/2/pwd'},
 'pyclbr': {'description': 'Python class browser support',
  'url': 'https://pymotw.com/2/pyclbr'},
 'pydoc': {'description': 'Online help for Python modules',
  'url': 'https://pymotw.com/2/pydoc'},
 'random': {'description': 'Pseudorandom number generators',
  'url': 'https://pymotw.com/2/random'},
 're': {'description': 'Searching within and changing text using formal patterns.',
  'url': 'https://pymotw.com/2/re'},
 'readline': {'description': 'Interface to the GNU readline library',
  'url': 'https://pymotw.com/2/readline'},
 'resource': {'description': 'System resource management',
  'url': 'https://pymotw.com/2/resource'},
 'rlcompleter': {'description': 'Adds tab-completion to the interactive interpreter',
  'url': 'https://pymotw.com/2/rlcompleter'},
 'robotparser': {'description': 'Internet spider access control',
  'url': 'https://pymotw.com/2/robotparser'},
 'sched': {'description': 'Generic event scheduler.',
  'url': 'https://pymotw.com/2/sched'},
 'select': {'description': 'Wait for I/O Efficiently',
  'url': 'https://pymotw.com/2/select'},
 'shelve': {'description': 'Persistent storage of arbitrary Python objects',
  'url': 'https://pymotw.com/2/shelve'},
 'shlex': {'description': 'Lexical analysis of shell-style syntaxes.',
  'url': 'https://pymotw.com/2/shlex'},
 'shutil': {'description': 'High-level file operations.',
  'url': 'https://pymotw.com/2/shutil'},
 'signal': {'description': 'Receive notification of asynchronous system events',
  'url': 'https://pymotw.com/2/signal'},
 'site': {'description': 'Site-wide configuration',
  'url': 'https://pymotw.com/2/site'},
 'smtpd': {'description': 'Includes classes for implementing SMTP servers.',
  'url': 'https://pymotw.com/2/smtpd'},
 'smtplib': {'description': 'Simple mail transfer protocol client.',
  'url': 'https://pymotw.com/2/smtplib'},
 'socket': {'description': 'Network communication',
  'url': 'https://pymotw.com/2/socket'},
 'sqlite3': {'description': 'Embedded relational database',
  'url': 'https://pymotw.com/2/sqlite3'},
 'string': {'description': 'Contains constants and classes for working with text.',
  'url': 'https://pymotw.com/2/string'},
 'struct': {'description': 'Convert between strings and binary data.',
  'url': 'https://pymotw.com/2/struct'},
 'subprocess': {'description': 'Work with additional processes',
  'url': 'https://pymotw.com/2/subprocess'},
 'sys': {'description': 'System-specific configuration',
  'url': 'https://pymotw.com/2/sys'},
 'sysconfig': {'description': 'Interpreter Compile-time Configuration',
  'url': 'https://pymotw.com/2/sysconfig'},
 'tabnanny': {'description': 'Scan Python source code looking for suspicious indentation.',
  'url': 'https://pymotw.com/2/tabnanny'},
 'tarfile': {'description': 'Tar archive access',
  'url': 'https://pymotw.com/2/tarfile'},
 'tempfile': {'description': 'Create temporary filesystem resources.',
  'url': 'https://pymotw.com/2/tempfile'},
 'textwrap': {'description': 'Formatting text by adjusting where line breaks occur in a paragraph.',
  'url': 'https://pymotw.com/2/textwrap'},
 'threading': {'description': 'Manage several concurrent threads of execution.',
  'url': 'https://pymotw.com/2/threading'},
 'time': {'description': 'Functions for manipulating clock time',
  'url': 'https://pymotw.com/2/time'},
 'timeit': {'description': 'Time the execution of small bits of Python code.',
  'url': 'https://pymotw.com/2/timeit'},
 'trace': {'description': 'Follow Python statements as they are executed.',
  'url': 'https://pymotw.com/2/trace'},
 'traceback': {'description': 'Extract, format, and print exceptions and stack traces.',
  'url': 'https://pymotw.com/2/traceback'},
 'unittest': {'description': 'Automated testing framework',
  'url': 'https://pymotw.com/2/unittest'},
 'urllib': {'description': "Accessing remote resources that don't need authentication, cookies, etc.",
  'url': 'https://pymotw.com/2/urllib'},
 'urllib2': {'description': 'Library for opening URLs.',
  'url': 'https://pymotw.com/2/urllib2'},
 'urlparse': {'description': 'Split URL into component pieces.',
  'url': 'https://pymotw.com/2/urlparse'},
 'uuid': {'description': 'Universally unique identifiers',
  'url': 'https://pymotw.com/2/uuid'},
 'warnings': {'description': 'Deliver non-fatal alerts to the user about issues encountered when running a program.',
  'url': 'https://pymotw.com/2/warnings'},
 'weakref': {'description': 'Refer to an "expensive" object, but allow it to be garbage collected if there are no other non-weak references.',
  'url': 'https://pymotw.com/2/weakref'},
 'webbrowser': {'description': 'Displays web pages',
  'url': 'https://pymotw.com/2/webbrowser'},
 'whichdb': {'description': 'Identify DBM-style database formats',
  'url': 'https://pymotw.com/2/whichdb'},
 'xmlrpclib': {'description': 'Client-side library for XML-RPC communication.',
  'url': 'https://pymotw.com/2/xmlrpclib'},
 'zipfile': {'description': 'Read and write ZIP archive files.',
  'url': 'https://pymotw.com/2/zipfile'},
 'zipimport': {'description': 'Load Python code from inside ZIP archives.',
  'url': 'https://pymotw.com/2/zipimport'},
 'zlib': {'description': 'Low-level access to GNU zlib compression library',
  'url': 'https://pymotw.com/2/zlib'}}


if __name__ == '__main__':
    print_random_module()
